/** Runtime event taxonomy (AGENT_RUNTIME.md §17). */

export const TASK_EVENT_TYPES = {
  RUN_STARTED: "RUN_STARTED",
  STATE_CHANGED: "STATE_CHANGED",
  CONTEXT_BUILT: "CONTEXT_BUILT",
  MODEL_ROUTE_SELECTED: "MODEL_ROUTE_SELECTED",
  MODEL_INVOCATION_RECORDED: "MODEL_INVOCATION_RECORDED",
  PLAN_CREATED: "PLAN_CREATED",
  PLAN_APPROVED: "PLAN_APPROVED",
  PLAN_REJECTED: "PLAN_REJECTED",
  PLAN_REVISION_REQUESTED: "PLAN_REVISION_REQUESTED",
  CHECKPOINT_CREATED: "CHECKPOINT_CREATED",
  CHECKPOINT_SKIPPED: "CHECKPOINT_SKIPPED",
  TOOL_REQUESTED: "TOOL_REQUESTED",
  TOOL_APPROVED: "TOOL_APPROVED",
  TOOL_DENIED: "TOOL_DENIED",
  TOOL_STARTED: "TOOL_STARTED",
  TOOL_COMPLETED: "TOOL_COMPLETED",
  TOOL_FAILED: "TOOL_FAILED",
  REPLAN_STARTED: "REPLAN_STARTED",
  CANCEL_REQUESTED: "CANCEL_REQUESTED",
  PAUSE_REQUESTED: "PAUSE_REQUESTED",
  VERIFICATION_STARTED: "VERIFICATION_STARTED",
  VERIFICATION_COMPLETED: "VERIFICATION_COMPLETED",
  RUN_COMPLETED: "RUN_COMPLETED",
  RUN_FAILED: "RUN_FAILED",
  RUN_CANCELLED: "RUN_CANCELLED",
  RUN_INTERRUPTED: "RUN_INTERRUPTED",
  APPROVAL_GRANTED: "APPROVAL_GRANTED",
  APPROVAL_DENIED: "APPROVAL_DENIED",
  APPROVAL_EXPIRED: "APPROVAL_EXPIRED",
  POLICY_SNAPSHOT_RECORDED: "POLICY_SNAPSHOT_RECORDED",
  MODEL_TEXT_DELTA: "MODEL_TEXT_DELTA",
  RUN_BLOCKED_BY_REVIEW: "RUN_BLOCKED_BY_REVIEW",
} as const;

export type TaskEventType = (typeof TASK_EVENT_TYPES)[keyof typeof TASK_EVENT_TYPES];

/** Bounded execution limits every run must respect (AGENT_RUNTIME.md §6). */
export interface RunBounds {
  maxDurationMs: number;
  maxModelInvocations: number;
  maxToolCalls: number;
  maxReplans: number;
}

export const DEFAULT_RUN_BOUNDS: RunBounds = {
  maxDurationMs: 30 * 60 * 1000,
  maxModelInvocations: 12,
  maxToolCalls: 50,
  maxReplans: 3,
};
